#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-sandwich
Version  : 3.1.0
Release  : 77
URL      : https://cran.r-project.org/src/contrib/sandwich_3.1-0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sandwich_3.1-0.tar.gz
Summary  : Robust Covariance Matrix Estimators
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-zoo
BuildRequires : R-lme4
BuildRequires : R-lmtest
BuildRequires : R-zoo
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
## Robust Covariance Matrix Estimators
Model-robust standard error estimators for cross-sectional, time series,
clustered, panel, and longitudinal data. Modular object-oriented
implementation with support for many model objects, including: `lm`,
`glm`, `fixest`, `survreg`, `coxph`, `mlogit`, `polr`, `hurdle`, `zeroinfl`,
and beyond.

%prep
%setup -q -n sandwich
pushd ..
cp -a sandwich buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702948268

%install
export SOURCE_DATE_EPOCH=1702948268
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sandwich/CITATION
/usr/lib64/R/library/sandwich/DESCRIPTION
/usr/lib64/R/library/sandwich/INDEX
/usr/lib64/R/library/sandwich/Meta/Rd.rds
/usr/lib64/R/library/sandwich/Meta/data.rds
/usr/lib64/R/library/sandwich/Meta/features.rds
/usr/lib64/R/library/sandwich/Meta/hsearch.rds
/usr/lib64/R/library/sandwich/Meta/links.rds
/usr/lib64/R/library/sandwich/Meta/nsInfo.rds
/usr/lib64/R/library/sandwich/Meta/package.rds
/usr/lib64/R/library/sandwich/Meta/vignette.rds
/usr/lib64/R/library/sandwich/NAMESPACE
/usr/lib64/R/library/sandwich/NEWS.md
/usr/lib64/R/library/sandwich/R/sandwich
/usr/lib64/R/library/sandwich/R/sandwich.rdb
/usr/lib64/R/library/sandwich/R/sandwich.rdx
/usr/lib64/R/library/sandwich/data/InstInnovation.rda
/usr/lib64/R/library/sandwich/data/Investment.rda
/usr/lib64/R/library/sandwich/data/PetersenCL.rda
/usr/lib64/R/library/sandwich/data/PublicSchools.rda
/usr/lib64/R/library/sandwich/doc/index.html
/usr/lib64/R/library/sandwich/doc/sandwich-CL.R
/usr/lib64/R/library/sandwich/doc/sandwich-CL.Rnw
/usr/lib64/R/library/sandwich/doc/sandwich-CL.pdf
/usr/lib64/R/library/sandwich/doc/sandwich-OOP.R
/usr/lib64/R/library/sandwich/doc/sandwich-OOP.Rnw
/usr/lib64/R/library/sandwich/doc/sandwich-OOP.pdf
/usr/lib64/R/library/sandwich/doc/sandwich.R
/usr/lib64/R/library/sandwich/doc/sandwich.Rnw
/usr/lib64/R/library/sandwich/doc/sandwich.pdf
/usr/lib64/R/library/sandwich/doc/sim-CL.R
/usr/lib64/R/library/sandwich/doc/sim-CL.rda
/usr/lib64/R/library/sandwich/help/AnIndex
/usr/lib64/R/library/sandwich/help/aliases.rds
/usr/lib64/R/library/sandwich/help/figures/README-sandwich.svg
/usr/lib64/R/library/sandwich/help/paths.rds
/usr/lib64/R/library/sandwich/help/sandwich.rdb
/usr/lib64/R/library/sandwich/help/sandwich.rdx
/usr/lib64/R/library/sandwich/html/00Index.html
/usr/lib64/R/library/sandwich/html/R.css
/usr/lib64/R/library/sandwich/tests/Examples/sandwich-Ex.Rout.save
/usr/lib64/R/library/sandwich/tests/vcovCL.R
/usr/lib64/R/library/sandwich/tests/vcovCL.Rout.save
/usr/lib64/R/library/sandwich/tests/vcovPC.R
/usr/lib64/R/library/sandwich/tests/vcovPC.Rout.save
/usr/lib64/R/library/sandwich/tests/vcovPL.R
/usr/lib64/R/library/sandwich/tests/vcovPL.Rout.save
