#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-sandwich
Version  : 2.3
Release  : 1
URL      : https://cran.r-project.org/src/contrib/sandwich_2.3-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sandwich_2.3-4.tar.gz
Summary  : Robust Covariance Matrix Estimators
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: R-zoo
Requires: R-car
Requires: R-lmtest
BuildRequires : R-car
BuildRequires : R-lmtest
BuildRequires : R-zoo
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n sandwich

%build

%install
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library sandwich
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library sandwich


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sandwich/CITATION
/usr/lib64/R/library/sandwich/DESCRIPTION
/usr/lib64/R/library/sandwich/INDEX
/usr/lib64/R/library/sandwich/Meta/Rd.rds
/usr/lib64/R/library/sandwich/Meta/data.rds
/usr/lib64/R/library/sandwich/Meta/hsearch.rds
/usr/lib64/R/library/sandwich/Meta/links.rds
/usr/lib64/R/library/sandwich/Meta/nsInfo.rds
/usr/lib64/R/library/sandwich/Meta/package.rds
/usr/lib64/R/library/sandwich/Meta/vignette.rds
/usr/lib64/R/library/sandwich/NAMESPACE
/usr/lib64/R/library/sandwich/NEWS
/usr/lib64/R/library/sandwich/R/sandwich
/usr/lib64/R/library/sandwich/R/sandwich.rdb
/usr/lib64/R/library/sandwich/R/sandwich.rdx
/usr/lib64/R/library/sandwich/data/Investment.rda
/usr/lib64/R/library/sandwich/data/PublicSchools.rda
/usr/lib64/R/library/sandwich/doc/index.html
/usr/lib64/R/library/sandwich/doc/sandwich-OOP.R
/usr/lib64/R/library/sandwich/doc/sandwich-OOP.Rnw
/usr/lib64/R/library/sandwich/doc/sandwich-OOP.pdf
/usr/lib64/R/library/sandwich/doc/sandwich.R
/usr/lib64/R/library/sandwich/doc/sandwich.Rnw
/usr/lib64/R/library/sandwich/doc/sandwich.pdf
/usr/lib64/R/library/sandwich/help/AnIndex
/usr/lib64/R/library/sandwich/help/aliases.rds
/usr/lib64/R/library/sandwich/help/paths.rds
/usr/lib64/R/library/sandwich/help/sandwich.rdb
/usr/lib64/R/library/sandwich/help/sandwich.rdx
/usr/lib64/R/library/sandwich/html/00Index.html
/usr/lib64/R/library/sandwich/html/R.css
